# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DIA6rZu+hGyFVeaJCTJaRGb+g2Bzoeelqh3UkzJ+G99M6LMV9azcS3JhSFbXQX+taFbwo2eFDsozklR86O1xiJ3Y5MfkfeW70bOeZokg7ygCfjXXN4IcdNFGAVCo2s9qpY54OZw9rDC/r3LjlukUzqqhm1taXHPGPexy2aiIz1wHGFzNNJPCyVDMhmdjbOCpyUl0T4by/o13J/PJb4sFtyP5XgEPP0DOs7baomjb8XIkGSrPOnZePUFsQX8WnQXzFX5fN/7COBONL/HXWxs43vkJ59tHr0eMliDtMf235tyF+Ex2hatTdimLIfWQ1EufWA6bbgAdGE4pxBBSf5OuFSsLq/294bn5xarloYP9zyqUWm+tkDEWJRb5cwJMRLUCTEdOxhyMzDBvfwy1IOQqDbeD5EQaa7VDtBYaGIdvhvVRXAYtOnr2IDT5mzXMi0GYBPiioW/bPH9uJT+J46RQgZit5IsFf+KHX4UuK4RpM+NeXFfZTtawUsnPMDwcY899m+N2b6xukp6LFIHLY5zNOzWZEAFelhZA4KqsEwXjekPfQlBbg2MVt5YCqfA2hkLgvkAcaX0s6lZFjdBUoY9DcUXNcPZ3yaDbNQeY5rohDoUuMd+jEZ/hy2Ao3E8CU1Vk9kTM7JM3fmMV1MvfGdV8A59UY04VCXnhWDOaEDlXx0M="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
