travis:
  secure:
    BINSTAR_TOKEN: JDjt/5umokJBqnSbWY0ybOy/tEf1ffjrtdInIovHANYIMpzwegE75vF+O0tHzGqF1G2f3YckZ3LOsSFs7D7ZI6G3EiYdm4tdItn86Q1138HwUzPudKLxPFd44nt/0oM21+G8q6WcwIrwsh8BYLG3t5ZQkLrYvgEw3zvjTA8GYAj3Tlt88W2qJndXKuPsGRE3YSa2hG7h9Ioq/X5ni/e/Kv2iaDAg5YRhIE61QTY3BPsezxKHuOkdPxroMLRElfsxVvT2nrdlYgRUxpjPgEWXsANm1iNTn+nbStCMblDXTV6AuyEE28pV7lInL2CW2/m/lUlqRt96CWO2hoEsqr9COLSVQ6GdRcGYHSTHl2gKYhZo1ZG0MfTPptNHNYUxzTZHQarWDEbKbXVH7ql/xz3bOZNc9FFklbRU3Gg2XFgR6EJzmEWyGISTP8Kp6rl5dp7Zq4gUvta+yFdonBNMXwcA/2OkX/evbMBm/mT8kV2NRLsgvsgUJyS8Un4TEpHLWqx+hJ1X9bIpW33fs9u7AfRvvHWC8LeThxJqlGG5DL2X1iDJtBMIJOIhSz5+eE2D0g8r96AzFYP41GtnPnDk6H4mstWuBJsR3jbCjpQ7sEvPo93Ow3ZI2s0Ie+EUz9ZwyC73D2aszTRlxSt7rzQpkAYy+nFAjzcIWror7/99CFNKYno=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
