travis:
  secure:
    BINSTAR_TOKEN: DIA6rZu+hGyFVeaJCTJaRGb+g2Bzoeelqh3UkzJ+G99M6LMV9azcS3JhSFbXQX+taFbwo2eFDsozklR86O1xiJ3Y5MfkfeW70bOeZokg7ygCfjXXN4IcdNFGAVCo2s9qpY54OZw9rDC/r3LjlukUzqqhm1taXHPGPexy2aiIz1wHGFzNNJPCyVDMhmdjbOCpyUl0T4by/o13J/PJb4sFtyP5XgEPP0DOs7baomjb8XIkGSrPOnZePUFsQX8WnQXzFX5fN/7COBONL/HXWxs43vkJ59tHr0eMliDtMf235tyF+Ex2hatTdimLIfWQ1EufWA6bbgAdGE4pxBBSf5OuFSsLq/294bn5xarloYP9zyqUWm+tkDEWJRb5cwJMRLUCTEdOxhyMzDBvfwy1IOQqDbeD5EQaa7VDtBYaGIdvhvVRXAYtOnr2IDT5mzXMi0GYBPiioW/bPH9uJT+J46RQgZit5IsFf+KHX4UuK4RpM+NeXFfZTtawUsnPMDwcY899m+N2b6xukp6LFIHLY5zNOzWZEAFelhZA4KqsEwXjekPfQlBbg2MVt5YCqfA2hkLgvkAcaX0s6lZFjdBUoY9DcUXNcPZ3yaDbNQeY5rohDoUuMd+jEZ/hy2Ao3E8CU1Vk9kTM7JM3fmMV1MvfGdV8A59UY04VCXnhWDOaEDlXx0M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
