travis:
  secure:
    BINSTAR_TOKEN: Qgnb6P1V5Jpolf9FXEEZ9qg2mrYSbU741rzU4Nks1YrYjvMH8INq7KpyV1je6EMPUOmtbv6hFIyD6mW618Pzpk8gWEsxhvKNSMynbU86bZFYo9w2Qe5MSWcYWRMwP5G6aExY8glfpPIROwVsM4h6nKX+k0x24P8GjLVQpczUO2GxdY8ZXtq1Wq9Nl4GyPltYc5BcJGEK1zyPOiiLB1e4/F1xUCdeiQc5OYbrBqIXqIv5uSPyO85F0TpV6lRuUjZvidFJ8h+6Q6x05/PFxwyRHBpnGlk+DeXwsaiISYTOjM/mRp25Zi1EQMUjk30eECcNamcAX10X7TLZSxOC5Ia9Nlg/POoM6wePvpsGkU5Z7FDylGtjvxIOKbOwHFZO+5yJ2UFm8DqgpYm0qHr3/dCZ2z3aZb9r8xPnvxoA3N1PuZVshn0+1I2VJt+/8YiEk8vJUB6hMZZmydyxDnUxxVv4J0N0/QtI+aJnEeXb9SOnNPFw6BPos7060aFRS7rpO5pUiHls0ppNkERj7RB/mn89X2VHVaa9b435JpQzl09E0x/nrbkjxGjDJNfut6XCYfJfNQE/dxZlbaF27nGWI061JFwap/wt14JNnG19vftROhW34aeVjneJpXqxpbyGNZafbdK9PHUr5Ljb+MqjRv9LkX2rpBItbF+jgJw/OuvcVXg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
